openapi: 3.1.0
x-stoplight:
  id: gt7vkhwftewdk
info:
  title: Wordle Dev Challenge
  version: '1.0'
servers:
  - url: 'http:/dev-challenge.test'
    description: local
paths:
  /api/guesses:
    post:
      summary: Submit a guess
      operationId: post-guess
      responses:
        '201':
          description: Guess was successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameStatus'
              examples:
                Single guess submitted:
                  value:
                    guesses:
                      - - letter: B
                          status: wrong_location
                        - letter: A
                          status: incorrect
                        - letter: C
                          status: correct
                        - letter: O
                          status: wrong_location
                        - letter: 'N'
                          status: incorrect
                    word: null
                    status: playing
        '400':
          description: Game currently not in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        '401':
          description: 'Invalid Bearer token, or Bearer token was not provided'
        '409':
          description: User has reached their maximum number of guesses
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        '422':
          description: Submitted guess does not match the required rules
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    message: string
                    errors:
                      - guess:
                          - Guess must be 5 characters
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        guess:
                          type: array
                          items:
                            type: string
                      required:
                        - guess
                required:
                  - message
                  - errors
              examples:
                Validation Error:
                  value:
                    message: string
                    errors:
                      - guess:
                          - Guess must be 5 characters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                guess:
                  type: string
                  minLength: 5
                  maxLength: 5
                  pattern: '^[A-Z]{5}'
            examples:
              Submitting a guess:
                value:
                  guess: BACON
        description: ''
      description: |-
        Submit a guess for the current word.

        - Must be 5 uppercase alpha characters
        - There is a maximum of 6 guesses allowed, any further guesses will be rejected
    parameters: []
  /api/game:
    get:
      summary: Get the current game status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameStatus'
        '400':
          description: Game not in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
      operationId: get-game
components:
  schemas:
    GuessLetter:
      title: Guess
      x-stoplight:
        id: 33a2f94df7e9f
      type: object
      additionalProperties: false
      properties:
        letter:
          type: string
          minLength: 1
          maxLength: 1
          example: S
        status:
          type: string
          enum:
            - correct
            - incorrect
            - wrong_location
      required:
        - letter
        - status
    GameStatus:
      title: GameStatus
      x-stoplight:
        id: rszl27t2ue4k9
      type: object
      properties:
        guesses:
          type: array
          minItems: 0
          maxItems: 6
          items:
            $ref: '#/components/schemas/Guess'
        word:
          type:
            - string
            - 'null'
          description: 'If the status is won or lost, the word will be here, otherwise it will be null'
          example: BACON
        status:
          type: string
          enum:
            - playing
            - won
            - lost
          example: playing
      required:
        - guesses
        - word
        - status
    Guess:
      title: Guess
      x-stoplight:
        id: ig9tuk6hb8g7n
      type: array
      minItems: 5
      maxItems: 5
      items:
        $ref: '#/components/schemas/GuessLetter'
      examples:
        - - letter: B
            status: wrong_location
          - letter: A
            status: incorrect
          - letter: C
            status: correct
          - letter: O
            status: wrong_location
          - letter: 'N'
            status: incorrect
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
